version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    networks:
         testing_net:
             ipv4_address: 172.28.1.1
    restart: always
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresql
      - mosquitto

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    networks:
         testing_net:
             ipv4_address: 172.28.1.2
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-server

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    networks:
         testing_net:
             ipv4_address: 172.28.1.3
    restart: always
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on:
      - mosquitto

  postgresql:
    image: postgres:9.6-alpine
    networks:
         testing_net:
             ipv4_address: 172.28.1.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    networks:
         testing_net:
             ipv4_address: 172.28.1.5
    restart: always
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:2
    networks:
         testing_net:
             ipv4_address: 172.28.1.6
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  postgresqldata:
  redisdata:

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16